- name: "Development"
  description: "Development"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - cmake
    - cuttlefish
    - gitahead
    - kompare
- name: "Password Manager"
  description: "Password managers"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - keepassxc
    - 1password
- name: "Privacy"
  description: "Privacy"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - tor
    - privoxy
- name: "Virtualbox for Linux or Linux-lts kernel"
  description: "Installs virtualbox for or linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers